WIP: [SE-3253] Fix translations for edx-platform
edx-olive/edx-platform pull request #37
Opened 2020-10-19 06:26 UTC by pkulkark

This PR fixes the following translation strings from the spreadsheet in edx-platform code:

- Line 1: Dashboard
- Lines 93 and 94: the word "Download" is translated but the rest ("SubRip (.srt) file") isn't

2020-10-30 02:16 UTC, clemente requested changes
@pkulkark 
- I tested „dashboard“, it's there.
- How can I test the „partially correct“? From the Campus screenshot I don't know which type of problem is that.
- The „download .srt“: if we need to change the inner workings, we'd have to upstream it (I think…). Could you check whether it's something that requires upstreaming in the latest version too? Or how to do it without upstreaming? The extra changes we're doing would create debt if we don't upstream them. I don't know a clear solution to this.  I commented on that particular line too

2020-11-01 11:42 UTC, clemente commented on lms/templates/video.html
> +                        <% dtext = dname + filename %>
@pkulkark After comments in the ticket: we shouldn't change this old code base in ways that would be hard to upstream. So we should prefer the easy workarounds like for instance „Download .srt“. This PR would become much simpler.
Sorry for having to revert it. We can use the upstreamability criteria to decide whether to do similar changes in the future.

You can confirm this with Campus and block this until then, since this one isn't urgent.

2021-05-17 08:08 UTC, nizarmah requested changes
I left a couple of comments. The polls and drag and drop xblock changes are not showing up on Stage, which is a bit confusing as well 😕

2021-05-17 08:08 UTC, nizarmah commented on common/lib/xmodule/xmodule/capa_base.py
> +                answer_notification_message = ungettext("Answer submitted.")
I searched through the spreadsheet, and I can't find any of the ""Answer submitted" terms requested to be translated.

2021-05-17 08:08 UTC, nizarmah commented on conf/locale/he/LC_MESSAGES/django.po
> +msgstr "אזור אישי"
I verified this 👍🏼

2021-05-17 08:08 UTC, nizarmah commented on conf/locale/he/LC_MESSAGES/djangojs.po
> +msgstr "אזור אישי"
I verified this as well 👍🏼

2021-05-17 08:08 UTC, nizarmah commented on requirements/edx/github.txt
> +-e git+https://github.com/open-craft/xblock-drag-and-drop-v2@2c63bfd3202dba3f7934e1740bffed41b2031283#egg=xblock-drag-and-drop-v2==2.0.18
Can you please link the pull request for this change?

2021-05-17 08:08 UTC, nizarmah commented on requirements/edx/github.txt
> +-e git+https://github.com/open-craft/xblock-poll@8c26bc94a0b4d82b6e75d718a3fc76fd104238aa#egg=xblock-poll
Can you please link the pull request for this change?

2021-05-17 08:15 UTC, pkulkark commented on common/lib/xmodule/xmodule/capa_base.py
> +                    answer_notification_message = ungettext("Partially Correct")
@nizarmah Yup, the spreadsheet incorrectly mentions "ORA" but ORA does not have this option. Also, the translations are slight differring because of the points assigned. I wasn't able to get the component working without any points assigned. Not sure why!

2021-05-17 08:16 UTC, pkulkark commented on common/lib/xmodule/xmodule/capa_base.py
> +                    answer_notification_message = ungettext("Incorrect")
@nizarmah Same thing here. It's due to the the points assigned that the text is slightly different.

2021-05-17 08:16 UTC, pkulkark commented on common/lib/xmodule/xmodule/capa_base.py
> +                    answer_notification_message = ungettext("Correct")
Same thing here

2021-05-17 08:17 UTC, pkulkark commented on common/lib/xmodule/xmodule/capa_base.py
> +                answer_notification_message = ungettext("Answer submitted.")
Ah that must've been removed. It was there earlier. I think it's fine to leave it in.

2021-07-19 21:37 UTC, clemente commented
Closing PR since the translations PRs we had to fix before the upgrade have been merged. We can create a new PR to resume working on these translations after we have upgraded to Koa (or later), though the texts may have changed by then. [More details](https://tasks.opencraft.com/browse/SE-3253?focusedCommentId=213675&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-213675).

2021-07-19 21:37 UTC, closed without merging